sudo: required
services:
  - docker # need a copy of docker

before_install:
  - docker build -t docker1875/docker-react -f Dockerfile.dev . #build docker image before test run. -f: force , will get a id of image. 

script:
  - docker run docker1875/docker-react npm run test -- --coverage
  