sudo: required
services:
  - docker # need a copy of docker

before_install:
  - docker build -t docker1875/docker-react -f Dockerfile.dev . #build docker image before test run. -f: force , will get a id of image. 

script:
  - docker run docker1875/docker-react npm run test -- --coverage

#DockerReact-env.qipt3jpswm.us-east-2.elasticbeanstalk.com
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-330717343488"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: "$AWS_SECRET_KEY"
  